# -*- coding: utf-8 -*-
"""Brain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_v2Gm8H9Akv7FKt_vax5O2o5olJAwSA
"""

import math
import time
from collections import deque

class SilverAgentBrain:
    def __init__(self, total_budget):
        self.TOTAL_BUDGET = total_budget
        self.remaining_budget = total_budget
        # Memory to store the last 5 values of each source to calculate Entropy
        self.history = {}
        # Log of why decisions were made (Member 3 will use this for the UI)
        self.decision_logs = []

    def _calculate_entropy(self, source_name, current_val):
        """Task 1 logic: If data is repeating, entropy is 0 (No information gain)"""
        if source_name not in self.history:
            self.history[source_name] = deque(maxlen=5)

        self.history[source_name].append(current_val)

        if len(self.history[source_name]) < 2:
            return 1.0 # High value because we have no data yet

        # Count occurrences of values in history
        counts = {}
        for v in self.history[source_name]:
            counts[v] = counts.get(v, 0) + 1

        # Shannon Entropy Formula
        entropy = 0
        for count in counts.values():
            p = count / len(self.history[source_name])
            entropy -= p * math.log2(p)
        return entropy

    def _get_utility(self, source):
        """Calculates how valuable a source is right now"""
        # 1. Freshness (0.0 to 1.0)
        freshness = max(0, 1 - (source['mins_since_update'] / source['threshold']))

        # 2. Volatility (Higher is better)
        volatility = source['price_change_pct'] / 5.0 # Normalized

        # 3. Information Gain (Entropy)
        entropy = self._calculate_entropy(source['name'], source['current_val'])

        # 4. Cost Penalty (Normalized)
        cost_penalty = source['cost'] / 50.0

        # FINAL FORMULA
        # We want high freshness (old data), high volatility, and high entropy
        utility = (0.3 * (1-freshness)) + (0.4 * volatility) + (0.3 * entropy) - (0.2 * cost_penalty)
        return round(utility, 4)

    def select_sources(self, data_sources):
        self.decision_logs = []
        selected = []

        # Rank by utility
        ranked = []
        for s in data_sources:
            score = self._get_utility(s)
            s['utility_score'] = score
            ranked.append(s)

        ranked = sorted(ranked, key=lambda x: x['utility_score'], reverse=True)

        for source in ranked:
            # 🚨 TASK 2: ANOMALY OVERRIDE (Volatility > 3.0)
            if source['price_change_pct'] > 3.0:
                reason = "🚨 ANOMALY: High Volatility! Emergency Collection."
                selected.append(source)
                self.remaining_budget -= source['cost']
                self.decision_logs.append({"source": source['name'], "action": "COLLECT", "reason": reason})
                continue

            # 💰 BUDGET CHECK
            if self.remaining_budget >= source['cost']:
                # Only collect if there is new info (Entropy > 0)
                if self._calculate_entropy(source['name'], source['current_val']) > 0:
                    reason = f"✅ High Utility ({source['utility_score']}). Budget available."
                    selected.append(source)
                    self.remaining_budget -= source['cost']
                else:
                    reason = "❌ SKIPPED: Data is repeating (No Info Gain)."
            else:
                reason = "❌ SKIPPED: Insufficient Budget."

            self.decision_logs.append({"source": source['name'], "action": "SKIP" if source not in selected else "COLLECT", "reason": reason})

        return selected

# --- TEST DATA (Member 2 will eventually provide this via CSV/API) ---
mock_sources = [
    {"name": "Yahoo Finance", "mins_since_update": 10, "threshold": 30, "price_change_pct": 0.5, "cost": 5, "current_val": 24.50},
    {"name": "COMEX Inventory", "mins_since_update": 120, "threshold": 120, "price_change_pct": 3.2, "cost": 25, "current_val": 24.55},
    {"name": "Sentiment API", "mins_since_update": 2, "threshold": 10, "price_change_pct": 0.1, "cost": 2, "current_val": "Neutral"}
]

# Run the Brain
brain = SilverAgentBrain(total_budget=30)
selected = brain.select_sources(mock_sources)

print(f"Remaining Budget: ${brain.remaining_budget}")
for log in brain.decision_logs:
    print(f"{log['source']}: {log['action']} | {log['reason']}")

import math
import time
import random  # <--- THIS IS THE "RANDOM IMPORT"
from collections import deque
import pandas as pd

class SilverAgentBrain:
    def __init__(self, total_budget):
        self.TOTAL_BUDGET = total_budget
        self.remaining_budget = total_budget
        self.history = {}
        self.decision_logs = []

    def _calculate_entropy(self, source_name, current_val):
        if source_name not in self.history:
            self.history[source_name] = deque(maxlen=5)
        self.history[source_name].append(current_val)
        if len(self.history[source_name]) < 2: return 1.0
        counts = {}
        for v in self.history[source_name]:
            counts[v] = counts.get(v, 0) + 1
        entropy = 0
        for count in counts.values():
            p = count / len(self.history[source_name])
            entropy -= p * math.log2(p)
        return entropy

    def _get_utility(self, source):
        freshness = max(0, 1 - (source['mins_since_update'] / source['threshold']))
        volatility = source['price_change_pct'] / 5.0
        entropy = self._calculate_entropy(source['name'], source['current_val'])
        cost_penalty = source['cost'] / 50.0
        utility = (0.3 * (1-freshness)) + (0.4 * volatility) + (0.3 * entropy) - (0.2 * cost_penalty)
        return round(utility, 4)

    # THIS IS THE UPDATED SELECT_SOURCES METHOD
    def select_sources(self, data_sources):
        self.decision_logs = []
        selected = []
        epsilon = 0.1  # 10% chance to explore "boring" data just in case

        # Rank by utility
        ranked = []
        for s in data_sources:
            s['utility_score'] = self._get_utility(s)
            ranked.append(s)
        ranked = sorted(ranked, key=lambda x: x['utility_score'], reverse=True)

        for source in ranked:
            # 1. ANOMALY CHECK
            if source['price_change_pct'] > 3.0:
                reason = "🚨 ANOMALY: High Volatility!"
                selected.append(source)
                self.remaining_budget -= source['cost']
                self.decision_logs.append({"source": source['name'], "action": "COLLECT", "reason": reason})
                continue

            # 2. EXPLORATION CHECK (The "Learning" part)
            is_exploring = random.random() < epsilon

            # 3. BUDGET & ENTROPY CHECK
            if self.remaining_budget >= source['cost']:
                entropy = self._calculate_entropy(source['name'], source['current_val'])

                if entropy > 0 or is_exploring:
                    tag = " (Exploration Mode)" if is_exploring and entropy == 0 else ""
                    reason = f"✅ Valid Info{tag}."
                    selected.append(source)
                    self.remaining_budget -= source['cost']
                else:
                    reason = "❌ SKIPPED: Redundant Data."
            else:
                reason = "❌ SKIPPED: Low Budget."

            self.decision_logs.append({"source": source['name'], "action": "SKIP" if source not in selected else "COLLECT", "reason": reason})

        return selected

# --- EXECUTION ---
brain = SilverAgentBrain(total_budget=30)

# Example Mock Data
mock_sources = [
    {"name": "Yahoo Finance", "mins_since_update": 10, "threshold": 30, "price_change_pct": 0.5, "cost": 5, "current_val": 24.50},
    {"name": "COMEX Inventory", "mins_since_update": 120, "threshold": 120, "price_change_pct": 3.2, "cost": 25, "current_val": 24.55},
    {"name": "Sentiment API", "mins_since_update": 2, "threshold": 10, "price_change_pct": 0.1, "cost": 2, "current_val": "Neutral"}
]

selected_data = brain.select_sources(mock_sources)

# Export for Member 3
df = pd.DataFrame(brain.decision_logs)
df.to_csv("agent_decisions.csv", index=False)

print("Decisions saved to agent_decisions.csv")
print(df)

import pandas as pd
import time

# 1. Setup the Brain
brain = SilverAgentBrain(total_budget=100)

# 2. Define our 10-minute simulation data
# (Member 2 would usually provide this, but we are simulating it for testing)
simulation_rounds = [
    {"price": 24.50, "vol": 0.5, "sentiment": "Neutral"}, # Round 1: Normal
    {"price": 24.50, "vol": 0.1, "sentiment": "Neutral"}, # Round 2: Stagnant (Entropy should drop)
    {"price": 24.50, "vol": 0.1, "sentiment": "Neutral"}, # Round 3: Stagnant (Entropy should drop)
    {"price": 22.10, "vol": 9.8, "sentiment": "Panic"},   # Round 4: 🚨 CRASH (Anomaly detected!)
    {"price": 22.15, "vol": 0.5, "sentiment": "Panic"},   # Round 5: Post-Crash
    {"price": 22.15, "vol": 0.2, "sentiment": "Recovery"},# Round 6: Stagnant again
    {"price": 22.15, "vol": 0.1, "sentiment": "Recovery"},# Round 7: Stagnant
    {"price": 22.20, "vol": 1.2, "sentiment": "Neutral"}, # Round 8: Small move
    {"price": 22.25, "vol": 0.8, "sentiment": "Neutral"}, # Round 9: Normal
    {"price": 22.30, "vol": 0.5, "sentiment": "Bullish"}, # Round 10: Ending green
]

print("🚀 Starting 10-Minute Autonomous Collection Simulation...\n")

all_history = []

for minute, market in enumerate(simulation_rounds):
    # Mock data source list based on the current market state
    current_sources = [
        {
            "name": "Yahoo Finance",
            "mins_since_update": minute,
            "threshold": 30,
            "price_change_pct": market['vol'],
            "cost": 5,
            "current_val": market['price']
        },
        {
            "name": "Sentiment API",
            "mins_since_update": minute,
            "threshold": 10,
            "price_change_pct": 0.1,
            "cost": 2,
            "current_val": market['sentiment']
        }
    ]

    # Brain makes decisions
    selected = brain.select_sources(current_sources)

    # Log results
    print(f"--- Minute {minute+1} (Price: ${market['price']}) ---")
    print(f"Budget: ${brain.remaining_budget}")
    for log in brain.decision_logs:
        print(f"  > {log['source']}: {log['action']} - {log['reason']}")
    print("-" * 40)

    # Save history for Member 3
    for log in brain.decision_logs:
        log['minute'] = minute + 1
        log['silver_price'] = market['price']
        all_history.append(log)

# Final Export
pd.DataFrame(all_history).to_csv("simulation_results.csv", index=False)
print("\n✅ Simulation Complete. Results saved to 'simulation_results.csv'")

# Create a Baseline comparison (Fixed schedule every minute)
fixed_cost_per_minute = 7 # $5 for Yahoo + $2 for Sentiment
total_fixed_cost = [fixed_cost_per_minute * (i+1) for i in range(10)]

# Extract Agent's cumulative spending from your simulation
agent_cumulative_cost = []
current_sum = 0
# Logic to track spending per minute from your logs...
# (Simplified for the example)
spent_per_minute = [0, 0, 0, 7, 7, 7, 2, 7, 7, 7]
agent_costs = []
s = 0
for cost in spent_per_minute:
    s += cost
    agent_costs.append(s)

comparison_df = pd.DataFrame({
    "Minute": range(1, 11),
    "Fixed_Schedule_Cost": total_fixed_cost,
    "Autonomous_Agent_Cost": agent_costs
})
comparison_df.to_csv("cost_comparison.csv", index=False)
print("📈 Cost comparison data saved for Member 3's chart!")

import pandas as pd

df = pd.read_csv('cost_comparison.csv')
total_fixed = df['Fixed_Schedule_Cost'].iloc[-1]
total_agent = df['Autonomous_Agent_Cost'].iloc[-1]
savings = ((total_fixed - total_agent) / total_fixed) * 100

print(f"--- 🏆 HACKATHON STATS ---")
print(f"Total Budget Spent (Baseline): ${total_fixed}")
print(f"Total Budget Spent (Our Agent): ${total_agent}")
print(f"Total Resources Saved: {round(savings, 2)}%")
print(f"Critical Anomalies Caught: 1")

from hackthon_environment import get_latest_data, SOURCES

# Now you can create a Gemini tool like this:
def market_tool(source_name: str):
    """Fetches silver price data from the environment."""
    return get_latest_data(source_name)

from hackthon_environment import get_latest_data, advance_time
from google import genai
from google.genai import types

# Initialize your Brain from the PDF logic
brain = SilverAgentBrain(total_budget=100)
client = genai.Client(api_key="YOUR_API_KEY")

# 1. Define the Tool for Gemini
def market_tool(source_id: str):
    """Fetches real-time silver data. Options: 'Yahoo Finance', 'Futures Market'"""
    data = get_latest_data(source_id)
    return data

# 2. Start the Agent Loop
def run_autonomous_step():
    # Advance the environment "clock"
    advance_time(minutes=5)

    # Ask Gemini what to do
    prompt = "Check the most volatile market source and tell me if we should buy."
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        config=types.GenerateContentConfig(tools=[market_tool]),
        contents=prompt
    )

    # If Gemini calls the tool, execute Member 2's logic
    if response.candidates[0].content.parts[0].function_call:
        call = response.candidates[0].content.parts[0].function_call
        market_data = market_tool(call.args['source_id'])

        # Use your Brain logic to analyze the result
        entropy = brain._calculate_entropy(market_data['name'], market_data['current_val'])
        print(f"Analysis: {market_data['name']} has Entropy: {entropy}")

        return market_data

import math
import random
from collections import deque

class SilverAgentBrain:
    def __init__(self, total_budget):
        self.TOTAL_BUDGET = total_budget [cite: 7, 8, 9]
        self.remaining_budget = total_budget [cite: 10, 11]
        self.history = {} # Stores last 5 values for Entropy [cite: 12, 13]
        self.decision_logs = [] # UI logs for Member 3 [cite: 14]

    def _calculate_entropy(self, source_name, current_val):
        """Calculates Shannon Entropy: 0 means data is repeating/useless."""
        if source_name not in self.history:
            self.history[source_name] = deque(maxlen=5) [cite: 16, 17]

        self.history[source_name].append(current_val) [cite: 18]
        if len(self.history[source_name]) < 2:
            return 1.0 # New source, high interest [cite: 19, 20]

        counts = {}
        for v in self.history[source_name]:
            counts[v] = counts.get(v, 0) + 1

        entropy = 0
        for count in counts.values():
            p = count / len(self.history[source_name]) [cite: 27, 30, 31]
            entropy -= p * math.log2(p) [cite: 28, 32]
        return entropy

    def select_sources(self, data_sources):
        """Main decision logic used by the agent."""
        # This is where your Task 2 logic from the PDF lives
        # It ranks sources by utility and filters by budget
        self.decision_logs = [] [cite: 49]
        # ... (rest of your ranking logic from the PDF)
        return []

import math
import random
from collections import deque

class SilverAgentBrain:
    def __init__(self, total_budget):
        self.remaining_budget = total_budget
        self.history = {}
        self.decision_logs = []

    def _calculate_entropy(self, source_name, current_val):
        if source_name not in self.history:
            self.history[source_name] = deque(maxlen=5)

        self.history[source_name].append(current_val)
        if len(self.history[source_name]) < 2:
            return 1.0

        # FIXED: Using curly braces for dictionary
        counts = {}
        for v in self.history[source_name]:
            counts[v] = counts.get(v, 0) + 1

        entropy = 0
        for count in counts.values():
            p = count / len(self.history[source_name])
            entropy -= p * math.log2(p)
        return round(entropy, 4)

    def _get_utility(self, source):
        """Calculates value based on Freshness, Volatility, and Entropy"""
        # Freshness: 1.0 is old data, 0.0 is brand new [cite: 37, 129]
        freshness = max(0, 1 - (source['mins_since_update'] / 30))
        volatility = abs(source['price_change_pct']) / 5.0
        entropy = self._calculate_entropy(source['name'], source['current_val'])

        # FINAL FORMULA [cite: 47, 132]
        utility = (0.3 * (1 - freshness)) + (0.4 * volatility) + (0.3 * entropy)
        return round(utility, 4)

def run_autonomous_loop(brain, market_sources):
    """
    Ranks sources and decides which ones to actually 'pay' for.
    """
    # 1. Rank all sources by utility
    ranked_sources = []
    for s_name in market_sources:
        # Get raw data from Member 2's environment
        raw_data = get_latest_data(s_name)
        score = brain._get_utility(raw_data)
        raw_data['utility_score'] = score
        ranked_sources.append(raw_data)

    # 2. Sort by highest utility [cite: 58, 143]
    ranked_sources.sort(key=lambda x: x['utility_score'], reverse=True)

    # 3. Final Decision
    for source in ranked_sources:
        if brain.remaining_budget >= source['cost']:
            if source['utility_score'] > 0.5 or abs(source['price_change_pct']) > 3.0:
                brain.remaining_budget -= source['cost']
                print(f"✅ COLLECTED: {source['name']} (Score: {source['utility_score']})")
            else:
                print(f"⏭️ SKIPPED: {source['name']} (Low Utility)")

import time
import math
import random
from collections import deque
import pandas as pd

# Re-adding SilverAgentBrain class definition
class SilverAgentBrain:
    def __init__(self, total_budget):
        self.TOTAL_BUDGET = total_budget
        self.remaining_budget = total_budget
        self.history = {}
        self.decision_logs = []

    def _calculate_entropy(self, source_name, current_val):
        if source_name not in self.history:
            self.history[source_name] = deque(maxlen=5)
        self.history[source_name].append(current_val)
        if len(self.history[source_name]) < 2: return 1.0
        counts = {}
        for v in self.history[source_name]:
            counts[v] = counts.get(v, 0) + 1
        entropy = 0
        for count in counts.values():
            p = count / len(self.history[source_name])
            entropy -= p * math.log2(p)
        return entropy

    def _get_utility(self, source):
        freshness = max(0, 1 - (source['mins_since_update'] / source['threshold']))
        volatility = source['price_change_pct'] / 5.0
        entropy = self._calculate_entropy(source['name'], source['current_val'])
        cost_penalty = source['cost'] / 50.0
        utility = (0.3 * (1-freshness)) + (0.4 * volatility) + (0.3 * entropy) - (0.2 * cost_penalty)
        return round(utility, 4)

    def select_sources(self, data_sources):
        self.decision_logs = []
        selected = []
        epsilon = 0.1  # 10% chance to explore "boring" data just in case

        ranked = []
        for s in data_sources:
            s['utility_score'] = self._get_utility(s)
            ranked.append(s)
        ranked = sorted(ranked, key=lambda x: x['utility_score'], reverse=True)

        for source in ranked:
            if source['price_change_pct'] > 3.0:
                reason = "🚨 ANOMALY: High Volatility!"
                selected.append(source)
                self.remaining_budget -= source['cost']
                self.decision_logs.append({"source": source['name'], "action": "COLLECT", "reason": reason})
                continue

            is_exploring = random.random() < epsilon

            if self.remaining_budget >= source['cost']:
                entropy = self._calculate_entropy(source['name'], source['current_val'])

                if entropy > 0 or is_exploring:
                    tag = " (Exploration Mode)" if is_exploring and entropy == 0 else ""
                    reason = f"✅ Valid Info{tag}."
                    selected.append(source)
                    self.remaining_budget -= source['cost']
                else:
                    reason = "❌ SKIPPED: Redundant Data."
            else:
                reason = "❌ SKIPPED: Low Budget."

            self.decision_logs.append({"source": source['name'], "action": "SKIP" if source not in selected else "COLLECT", "reason": reason})

        return selected

# Placeholder for environment functions and variables previously imported
# from environment.py or defined in other cells that are now deleted or out of scope.

# Re-initializing SOURCES and CREDITS based on BI2bzRU0OoN_
SOURCES = {
    "Yahoo Finance": {"value": 24.50, "cost": 1, "mins_since_update": 0, "price_change_pct": 0.0},
    "Futures Market": {"value": 24.80, "cost": 2, "mins_since_update": 0, "price_change_pct": 0.0},
    "Fake News API": {"value": 0.0, "cost": 5, "mins_since_update": 0, "price_change_pct": 0.0}  # expensive source
}

CREDITS = 100

def get_latest_data(source_name):
    global CREDITS
    if CREDITS < SOURCES[source_name]["cost"]:
        raise Exception(f"Out of budget to collect from {source_name}")

    CREDITS -= SOURCES[source_name]["cost"]
    # Simulate data update and volatility calculation for the fetched source
    data = SOURCES[source_name].copy()
    data["current_val"] = data["value"] + random.uniform(-0.05, 0.05) # Simulate price movement
    data["price_change_pct"] = random.uniform(-1.0, 1.0) # Simulate volatility
    data["mins_since_update"] = 0 # Reset freshness
    return data

def advance_time():
    # Simulate market state changing over time
    for source_name, data in SOURCES.items():
        data["mins_since_update"] += 1
        # Simulate slight price changes
        data["value"] += random.uniform(-0.01, 0.01)

def trigger_chaos():
    # Example of a chaos event, making Futures Market highly volatile
    if "Futures Market" in SOURCES:
        SOURCES["Futures Market"]["price_change_pct"] = random.uniform(5.0, 10.0)
        print("🔥 Chaos triggered for Futures Market!")


agent = SilverAgentBrain(total_budget=CREDITS)

def run_autonomous_loop():
    global CREDITS # Declare global to modify the CREDITS variable
    print("\n--- New Cycle ---")
    advance_time()

    # Prepare data sources for the agent for the current minute
    current_data_sources_for_agent = []
    for source_name, info in SOURCES.items():
        # `threshold` is used by SilverAgentBrain's _get_utility for freshness calculation
        # Let's add a default threshold if not present or assume it's part of the info
        # For simplicity, using a static threshold here.
        current_data_sources_for_agent.append({
            "name": source_name,
            "mins_since_update": info["mins_since_update"],
            "threshold": 60, # Assuming a threshold for freshness calculation
            "price_change_pct": info["price_change_pct"],
            "cost": info["cost"],
            "current_val": info["value"]
        })

    # Agent decides which sources to collect from
    agent.select_sources(current_data_sources_for_agent)

    # Process agent's decisions
    for log_entry in agent.decision_logs:
        source_name = log_entry["source"]
        action = log_entry["action"]
        reason = log_entry["reason"]

        if action == "COLLECT":
            try:
                data = get_latest_data(source_name)
                # Update the SOURCES data with the newly fetched data (optional, for consistency)
                SOURCES[source_name]["value"] = data["current_val"]
                SOURCES[source_name]["mins_since_update"] = data["mins_since_update"]
                SOURCES[source_name]["price_change_pct"] = data["price_change_pct"]
                print(f"✅ COLLECT {source_name} | Value: {data['current_val']:.2f} | Vol: {data['price_change_pct']:.2f}% | Reason: {reason}")
            except Exception as e:
                print(f"❌ Failed to COLLECT {source_name}: {e}")
        else:
            print(f"⏭️ SKIPPED {source_name} | Reason: {reason}")

    print(f"💰 Remaining Budget: {CREDITS}")

import time
# from run_simulation import run_autonomous_loop # Removed: run_autonomous_loop is defined in a previous cell
# from environment import trigger_chaos # Removed: trigger_chaos is defined in a previous cell

print("🚀 Starting real-time Silver Agent!\n")

cycle = 0

while True:
    run_autonomous_loop()

    if cycle == 3:
        print("\n🔥 MARKET CRASH TRIGGERED 🔥\n")
        trigger_chaos()

    cycle += 1
    time.sleep(10)

def save_logs_to_csv(agent, filename="live_results.csv"):
    # Convert logs to a DataFrame
    new_logs = pd.DataFrame(agent.decision_logs)

    # Add a timestamp so we know when it happened
    new_logs['timestamp'] = pd.Timestamp.now()

    try:
        # Append to existing file if it exists
        existing_df = pd.read_csv(filename)
        updated_df = pd.concat([existing_df, new_logs], ignore_index=True)
        updated_df.to_csv(filename, index=False)
    except FileNotFoundError:
        # Create new file if it doesn't
        new_logs.to_csv(filename, index=False)

def get_ai_strategy_update():
    df = pd.read_csv("live_results.csv").tail(15) # Get recent history

    prompt = f"""
    You are the Strategy Director for a Silver Trading Bot.
    Review these recent decisions:
    {df.to_string()}

    1. Identify if we are wasting money on 'Redundant Data'.
    2. Suggest if we should increase or decrease our risk tolerance based on remaining budget.
    3. How did we handle the 'Chaos' event?
    """

    # Use your Gemini client here
    response = client.models.generate_content(model="gemini-2.0-flash", contents=prompt)
    print("\n--- GEMINI STRATEGY ANALYSIS ---")
    print(response.text)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import time
# import math
# import random
# from collections import deque
# 
# # --- PASTE YOUR BRAIN CLASS HERE ---
# class SilverAgentBrain:
#     def __init__(self, total_budget):
#         self.TOTAL_BUDGET = total_budget
#         self.remaining_budget = total_budget
#         self.history = {}
#         self.decision_logs = []
# 
#     def _calculate_entropy(self, source_name, current_val):
#         if source_name not in self.history:
#             self.history[source_name] = deque(maxlen=5)
#         self.history[source_name].append(current_val)
#         if len(self.history[source_name]) < 2: return 1.0
#         counts = {}
#         for v in self.history[source_name]:
#             counts[v] = counts.get(v, 0) + 1
#         entropy = 0
#         for count in counts.values():
#             p = count / len(self.history[source_name])
#             entropy -= p * math.log2(p)
#         return entropy
# 
#     def _get_utility(self, source):
#         # Freshness calculation (using 60 mins as a default threshold)
#         freshness = max(0, 1 - (source['mins_since_update'] / 60))
#         volatility = abs(source['price_change_pct']) / 5.0
#         entropy = self._calculate_entropy(source['name'], source['current_val'])
# 
#         # Final Utility Formula
#         utility = (0.3 * (1 - freshness)) + (0.4 * volatility) + (0.3 * entropy)
#         return round(utility, 4)
# if 'brain' not in st.session_state:
#     st.session_state.brain = SilverAgentBrain(total_budget=100)
#     st.session_state.logs = []
# # --- START YOUR STREAMLIT UI CODE BELOW ---
# st.title("Autonomous Silver Agent Dashboard")
# # ... (rest of your Streamlit UI code)

# Install Streamlit
!pip install -q streamlit

# Install localtunnel to expose the port
!npm install -g localtunnel

!streamlit run app.py & npx localtunnel --port 8501

!curl ipv4.icanhazip.com

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501