# -*- coding: utf-8 -*-
"""hackthon  environment creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLPnNfm7VWBD37kXzs4VfhzqnlFrt8nN
"""

import pandas as pd
# This creates the "Raw Data" Member 2 is supposed to provide
data = {
    'name': ['spot_silver', 'futures_silver'] * 5,
    'mins_since_update': [5, 5, 10, 10, 1, 1, 2, 2, 5, 5],
    'price_change_pct': [0.1, 0.1, 0.0, 0.0, 5.5, 5.2, 0.2, 0.2, 0.1, 0.1],
    'cost': [5, 7, 5, 7, 5, 7, 5, 7, 5, 7],
    'current_val': [24.50, 24.55, 24.50, 24.55, 22.10, 22.15, 22.12, 22.18, 22.20, 22.25]
}

df = pd.DataFrame(data)
df.to_csv('member2_market_data.csv', index=False)
print("✅ Member 2's Raw Data CSV has been created!")

from fastapi import FastAPI
from datetime import datetime, timedelta
import random

app = FastAPI(title="Silver Market Environment API")

MARKET_STATE = {
    "spot_price": {
        "price": 24.50,
        "volatility": 0.02,
        "last_updated": datetime.now(),
        "cost": 1
    },
    "futures_price": {
        "price": 24.80,
        "volatility": 0.04,
        "last_updated": datetime.now(),
        "cost": 2
    },
    "news_sentiment": {
        "price": 0.0,  # sentiment score
        "volatility": 0.5,
        "last_updated": datetime.now(),
        "cost": 1
    },
    "macro_signal": {
        "price": 0.1,
        "volatility": 0.005,
        "last_updated": datetime.now(),
        "cost": 3
    }
}
@app.post("/market/step")
def market_step(minutes: int = 10):
    for src, data in MARKET_STATE.items():

        # News causes rare shocks
        if src == "news_sentiment" and random.random() < 0.15:
            delta = random.uniform(-3, 3)

        # Futures react faster
        elif src == "futures_price":
            delta = random.uniform(-data["volatility"] * 3, data["volatility"] * 3)

        # Spot price slow drift
        elif src == "spot_price":
            delta = random.uniform(-data["volatility"], data["volatility"])

        # Macro is very slow
        else:
            delta = random.uniform(-data["volatility"], data["volatility"])

        data["price"] += delta
        data["last_updated"] += timedelta(minutes=minutes)

    return {"status": "silver market advanced", "minutes": minutes}

@app.get("/market/sources")
def get_market_sources():

    snapshot = {}

    for src, data in MARKET_STATE.items():
        minutes_old = (datetime.now() - data["last_updated"]).seconds / 60

        snapshot[src] = {
            "value": round(data["price"], 3),
            "minutes_since_update": minutes_old,
            "cost": data["cost"]
        }

    return snapshot

@app.post("/market/collect/{source_name}")
def collect_market_data(source_name: str):

    if source_name not in MARKET_STATE:
        return {"error": "invalid market source"}

    data = MARKET_STATE[source_name]

    response = {
        "source": source_name,
        "value": round(data["price"], 3),
        "fetched_at": datetime.now(),
        "cost": data["cost"]
    }
    # Reset freshness
    data["last_updated"] = datetime.now()

    return response

from datetime import datetime, timedelta
import random

MARKET_STATE = {
    "spot_price": {
        "price": 24.5,
        "volatility": 0.02,
        "last_updated": datetime.now(),
        "cost": 1
    },
    "futures_price": {
        "price": 24.8,
        "volatility": 0.04,
        "last_updated": datetime.now(),
        "cost": 2
    },
    "news_sentiment": {
        "price": 0.1,
        "volatility": 0.5,
        "last_updated": datetime.now(),
        "cost": 1
    }
}
EMERGENCY_ACTIVE = False
EMERGENCY_SOURCE = "futures_price"
EMERGENCY_VOLATILITY = 5.0
EMERGENCY_START_STEP = 4
EMERGENCY_DURATION = 3
def market_step(step_id, minutes=5):
    global EMERGENCY_ACTIVE

    # Activate emergency
    if step_id == EMERGENCY_START_STEP:
        EMERGENCY_ACTIVE = True
        MARKET_STATE[EMERGENCY_SOURCE]["volatility"] = EMERGENCY_VOLATILITY
        print("🚨 EMERGENCY TRIGGERED: Futures volatility = 5.0")

    # Deactivate emergency
    if EMERGENCY_ACTIVE and step_id == EMERGENCY_START_STEP + EMERGENCY_DURATION:
        EMERGENCY_ACTIVE = False
        MARKET_STATE[EMERGENCY_SOURCE]["volatility"] = 0.04
        print("✅ Emergency resolved: Volatility normalized")

    for src, data in MARKET_STATE.items():
        delta = random.uniform(
            -data["volatility"],
            data["volatility"]
        )

        data["price"] += delta
        data["last_updated"] += timedelta(minutes=minutes)
def get_market_feed():
    feed = {}

    for src, data in MARKET_STATE.items():
        feed[src] = {
            "value": round(data["price"], 3),
            "volatility": data["volatility"],
            "last_updated": data["last_updated"]
        }

    return feed
if __name__ == "__main__":

    for step in range(1, 10):
        print(f"\n--- STEP {step} ---")
        market_step(step)

        feed = get_market_feed()
        for src, info in feed.items():
            print(
                f"{src:15} | value={info['value']:>6} | vol={info['volatility']}"
            )
        # Define observed_volatility before using it
        observed_volatility = feed[EMERGENCY_SOURCE]["volatility"] # Assuming intent is to check emergency source volatility

        # Placeholder for trigger_emergency_mode function, as it's not defined
        def trigger_emergency_mode():
            print("Emergency mode triggered!")

        if observed_volatility > 2.0:
            trigger_emergency_mode()

import time
import random
import pandas as pd

ENV_STATE = {
    "spot_silver": {"value": 24.5, "cost": 1},
    "futures_silver": {"value": 24.8, "cost": 2}
}

PREV_VALUES = {k: v["value"] for k, v in ENV_STATE.items()}
MINS_SINCE_UPDATE = {k: 0 for k in ENV_STATE}

ALL_DATA_COLLECTED = []
def environment_loop(step_seconds=2, steps_to_run=5):
    global ALL_DATA_COLLECTED
    step_count = 0

    while step_count < steps_to_run:
        time.sleep(step_seconds)
        LIVE_DATA_FEED = []

        for name, data in ENV_STATE.items():
            # simulate market movement
            delta = random.uniform(-0.05, 0.05)
            data["value"] += delta

            prev = PREV_VALUES[name]
            pct_change = ((data["value"] - prev) / prev) * 100

            MINS_SINCE_UPDATE[name] += 1
            PREV_VALUES[name] = data["value"]

            LIVE_DATA_FEED.append({
                "name": name,
                "mins_since_update": MINS_SINCE_UPDATE[name],
                "price_change_pct": round(pct_change, 3),
                "cost": data["cost"],
                "current_val": round(data["value"], 3)
            })
        ALL_DATA_COLLECTED.extend(LIVE_DATA_FEED)
        step_count += 1

    df_market_data = pd.DataFrame(ALL_DATA_COLLECTED)
    df_market_data.to_csv('silver_market_data.csv', index=False)
    print("Silver market data saved to silver_market_data.csv")


environment_loop()

ENV_STATE = {
    "spot_price": {
        "value": 24.5,
        "minutes_since_update": 0,
        "cost": 1
    },
    "futures_price": {
        "value": 24.8,
        "minutes_since_update": 0,
        "cost": 2
    }
}
import time

def realtime_freshness_loop(step_seconds=2):
    """
    Increases minutes_since_update by 1 every few seconds
    so agent scores change in real time.
    """
    while True:
        time.sleep(step_seconds)

        for src, data in ENV_STATE.items():
            data["minutes_since_update"] += 1

        print("\n⏱ Freshness Update")
        for src, data in ENV_STATE.items():
            print(f"{src}: minutes_since_update = {data['minutes_since_update']}")
realtime_freshness_loop(step_seconds=2)
def compute_freshness(minutes_since_update):
    return max(0, 1 - minutes_since_update / 60)
def collect(source_id):
    ENV_STATE[source_id]["minutes_since_update"] = 0
    print(f"📥 Collected {source_id} → freshness reset")
def compute_utility(src):
    freshness = compute_freshness(ENV_STATE[src]["minutes_since_update"])
    cost = ENV_STATE[src]["cost"]
    return round(freshness - 0.1 * cost, 3)

def realtime_demo_loop():
    while True:
        time.sleep(2)

        for src in ENV_STATE:
            ENV_STATE[src]["minutes_since_update"] += 1

        print("\n📊 Live Agent Scores")
        for src in ENV_STATE:
            print(
                f"{src} | minutes={ENV_STATE[src]['minutes_since_update']} "
                f"| utility={compute_utility(src)}"
            )

import time
import random
import csv

# -----------------------------
# Initial silver market state
# -----------------------------
SOURCES = {
    "Yahoo Finance": {"value": 24.50, "cost": 1},
    "Futures Market": {"value": 24.80, "cost": 2},
    "News Sentiment": {"value": 0.0, "cost": 1}
}

PREV_VALUES = {k: v["value"] for k, v in SOURCES.items()}
MINS_SINCE_UPDATE = {k: 0 for k in SOURCES}

CSV_FILE = "silver_market_feed.csv"

# -----------------------------
# Stream data to CSV
# -----------------------------
def stream_silver_data_to_csv(step_seconds=2):
    with open(CSV_FILE, "w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "name",
                "mins_since_update",
                "price_change_pct",
                "cost",
                "current_val"
            ]
        )
        writer.writeheader()

        while True:
            time.sleep(step_seconds)

            for name, data in SOURCES.items():
                # Simulate market movement
                delta = random.uniform(-0.05, 0.05)
                data["value"] += delta

                prev = PREV_VALUES[name]
                price_change_pct = ((data["value"] - prev) / prev) * 100

                MINS_SINCE_UPDATE[name] += 1
                PREV_VALUES[name] = data["value"]

                writer.writerow({
                    "name": name,
                    "mins_since_update": MINS_SINCE_UPDATE[name],
                    "price_change_pct": round(price_change_pct, 3),
                    "cost": data["cost"],
                    "current_val": round(data["value"], 3)
                })

                f.flush()

import time
import random
import csv

# -----------------------------
# Initial silver market state
# -----------------------------
SOURCES = {
    "Yahoo Finance": {"value": 24.50, "cost": 1},
    "Futures Market": {"value": 24.80, "cost": 2},
    "News Sentiment": {"value": 0.0, "cost": 1},
    "Fake News": {"value": 25.00, "cost": 10}   # High cost source
}

PREV_VALUES = {k: v["value"] for k, v in SOURCES.items()}
MINS_SINCE_UPDATE = {k: 0 for k in SOURCES}

CSV_FILE = "silver_market_feed.csv"

# -----------------------------
# Stream data to CSV
# -----------------------------
def stream_silver_data_to_csv(step_seconds=60):
    with open(CSV_FILE, "w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "name",
                "mins_since_update",
                "price_change_pct",
                "cost",
                "current_val"
            ]
        )
        writer.writeheader()

        while True:
            time.sleep(step_seconds)

            for name, data in SOURCES.items():

                # ---- FAKE NEWS LOGIC ----
                if name == "Fake News":
                    # No change for first 5 minutes
                    if MINS_SINCE_UPDATE[name] < 5:
                        delta = 0.0
                    # Sudden spike after 5 minutes
                    elif MINS_SINCE_UPDATE[name] == 5:
                        delta = random.uniform(1.5, 2.5)  # BIG spike
                    else:
                        delta = random.uniform(-0.1, 0.1)

                # ---- NORMAL SOURCES ----
                else:
                    delta = random.uniform(-0.05, 0.05)

                data["value"] += delta

                prev = PREV_VALUES[name]
                price_change_pct = (
                    ((data["value"] - prev) / prev) * 100 if prev != 0 else 0
                )

                MINS_SINCE_UPDATE[name] += 1
                PREV_VALUES[name] = data["value"]

                writer.writerow({
                    "name": name,
                    "mins_since_update": MINS_SINCE_UPDATE[name],
                    "price_change_pct": round(price_change_pct, 3),
                    "cost": data["cost"],
                    "current_val": round(data["value"], 3)
                })

                f.flush()

CREDITS = 100

def get_latest_data(source_id):
    global CREDITS
    CREDITS -= SOURCES[source_id]["cost"]
    return latest_data

if CREDITS < 0:
    raise Exception("Out of budget")

import time
import random
import csv

# --------------------------------
# Market sources (Environment)
# --------------------------------
SOURCES = {
    "Yahoo Finance": {"value": 24.50, "cost": 1},
    "Futures Market": {"value": 24.80, "cost": 2},
    "Fake News API": {"value": 0.0, "cost": 5}  # expensive source
}

PREV_VALUES = {k: v["value"] for k, v in SOURCES.items()}
MINS_SINCE_UPDATE = {k: 0 for k in SOURCES}

CSV_FILE = "silver_market_feed.csv"

# Fake News behavior control
FAKE_NEWS_SILENT_MINUTES = 5
FAKE_NEWS_SPIKE_TRIGGERED = False
def stream_silver_data_to_csv(step_seconds=60):
    with open(CSV_FILE, "w", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "name",
                "mins_since_update",
                "price_change_pct",
                "cost",
                "current_val"
            ]
        )
        writer.writeheader()

        while True:
            time.sleep(step_seconds)

            for name, data in SOURCES.items():

                # --------------------------------
                # Fake News logic
                # --------------------------------
                if name == "Fake News API":
                    if MINS_SINCE_UPDATE[name] < FAKE_NEWS_SILENT_MINUTES:
                        delta = 0.0  # completely flat
                    elif not FAKE_NEWS_SPIKE_TRIGGERED:
                        delta = random.uniform(5.0, 8.0)  # BIG spike
                        globals()["FAKE_NEWS_SPIKE_TRIGGERED"] = True
                    else:
                        delta = random.uniform(-0.2, 0.2)

                # Normal market behavior
                else:
                    delta = random.uniform(-0.05, 0.05)

                data["value"] += delta

                prev = PREV_VALUES[name]
                price_change_pct = (
                    ((data["value"] - prev) / prev) * 100
                    if prev != 0 else 0.0
                )

                MINS_SINCE_UPDATE[name] += 1
                PREV_VALUES[name] = data["value"]

                writer.writerow({
                    "name": name,
                    "mins_since_update": MINS_SINCE_UPDATE[name],
                    "price_change_pct": round(price_change_pct, 3),
                    "cost": data["cost"],
                    "current_val": round(data["value"], 3)
                })

                f.flush()
# stream_silver_data_to_csv(step_seconds=60) # commented out to avoid infinite loop unless explicitly called
CREDITS = 100

def get_latest_data(source_id):
    global CREDITS
    CREDITS -= SOURCES[source_id]["cost"]

    latest_data = SOURCES[source_id]
    if CREDITS < 0:
        raise Exception("Out of budget")
    return latest_data